// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
// Created on Sun Mar 30 10:26:06 2025

hanming_decode_mif hanming_decode_mif_inst
(
	.clk_20MHz(clk_20MHz_sig) ,	// input  clk_20MHz_sig
	.hm_noise(hm_noise_sig) ,	// output  hm_noise_sig
	.cb_out(cb_out_sig) ,	// output [6:0] cb_out_sig
	.ss(ss_sig) ,	// output [2:0] ss_sig
	.ym_out(ym_out_sig) ,	// output [6:3] ym_out_sig
	.wuma(wuma_sig) ,	// output  wuma_sig
	.decode_out(decode_out_sig) ,	// output  decode_out_sig
	.m_sequence(m_sequence_sig) ,	// output  m_sequence_sig
	.code_out(code_out_sig) 	// output  code_out_sig
);

